### ISSUE TITLE
Removal of Files in `op` dir

### ISSUE THREAD

**Issue by wachsylon** [AtMoDat/atmodat_data_checker#87] opened 2021-11-01 10:35 UTC
Hi, 
this might be a very urgent issue. 
I tested
`run_checks -f /work/bm0021/cdo_incl_cmor/examples/example_interface.nc -op notebooks/`
from within the `atmodat_data_checker` dir. Afterwards, the notebooks were **removed** from the directory `notebooks`!

I also tested
`run_checks -f /work/bm0021/cdo_incl_cmor/examples/example_interface.nc -op /home/dkrz/k204210/`
for my home directory. I thought this command hangs up but now I think it might just have delted some files!

I try to find the bug.
@cehbrecht  @jkretz @atmodatcode 

Best,
Fabi

**Comment by wachsylon** [comment] 2021-11-01 10:43
https://github.com/AtMoDat/atmodat_data_checker/blob/96b7da708071629f61db1fbeb8ea187ca59204cb/atmodat_checklib/result_output/output_directory.py#L12

You have to revise this. It seems like removing too much. It is called by:
https://github.com/AtMoDat/atmodat_data_checker/blob/96b7da708071629f61db1fbeb8ea187ca59204cb/run_checks.py#L72

**Comment by jkretz** [comment] 2021-11-01 12:14
Before the `-op` option was added, the output directory was a fixed directory within the repository directory. Using the `shutil.rmtree(opath + '/')` therefore was a reasonable choice, as only well-defined directories were deleted.
When introducing the `-op` option, the `shutil.rmtree(opath + '/')` should also have been adapted, as it is a very dangerous way of deleting the output directory. In case `opath` is an empty string and with a `sudo`, this might even deleted the root directory.
I will work on it right away to improve it.

**Comment by jkretz** [comment] 2021-11-01 13:46
@wachsylon
I hope the issue is fixed with the PR I opened for it. While reviewing the -op option, I defined a dedicated directory into which the output was written and for development, I never use the `-op` option, causing me to never run across this serious issue, Sorry again for the inconvenience.

**Closed** 2021-11-03 07:40 UTC
